// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremiumCalculator.DAL;

namespace PremiumCalculator.DAL.Migrations
{
    [DbContext(typeof(PremiumDbContext))]
    [Migration("20210119114301_InitialDbCreation")]
    partial class InitialDbCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PremiumCalculator.Models.Occupation", b =>
                {
                    b.Property<int>("OccupationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RatingID")
                        .HasColumnType("int");

                    b.HasKey("OccupationID");

                    b.HasIndex("RatingID");

                    b.ToTable("Occupation");
                });

            modelBuilder.Entity("PremiumCalculator.Models.Rating", b =>
                {
                    b.Property<int>("RatingID")
                        .HasColumnType("int");

                    b.Property<double>("Factor")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("PremiumCalculator.Models.Occupation", b =>
                {
                    b.HasOne("PremiumCalculator.Models.Rating", "Rating")
                        .WithMany("Occupations")
                        .HasForeignKey("RatingID");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("PremiumCalculator.Models.Rating", b =>
                {
                    b.Navigation("Occupations");
                });
#pragma warning restore 612, 618
        }
    }
}
